require 'nightwatch/autoload'
require 'nightwatch/monitor'
require 'nightwatch/commit'
require 'nightwatch/config'
require 'nightwatch/middleware/main_thread'
require 'nightwatch/middleware/thread'
require 'nightwatch/defaults'
